### ISSUE TITLE
No pickup notifications showing.

### ISSUE THREAD

**Issue by jdamboeck** [Fuzss/pickupnotifier-fabric#4]
Made a new fabric profile with fabric-loader-0.12.8-1.17.1 and installed:

- fabric-api-0.44.0+1.17.jar
- ForgeConfigAPIPort-v2.0.0-1.17.1-Fabric.jar
- PuzzlesLib-v2.0.1-1.17.1-Fabric.jar
- PickUpNotifier-v2.1.0-1.17.1-Fabric.jar

Made a New World, hacked some wood, picked it up.

Result: No pickup notifications showing.

[latest.log](https://github.com/Fuzss/pickupnotifier-fabric/files/7653699/latest.log)

**Comment by Fuzss** [comment]
Hmm that's gonna be a tough one. I'm on Mac and everything works fine, but just tried Windows and it indeed doesn't work.

Could you please try to install my [Easy Magic](https://www.curseforge.com/minecraft/mc-mods/easy-magic-fabric) mod and tell me if the notifications show then? (I know this is really odd, but it worked for me on Windows consistently with that mod, and I want to make sure something like this is reproducible.)

**Comment by jdamboeck** [comment]
Yeah did that. Still nothing. To complicate the matter. I am not on windows too. Linux here.

[latest.log](https://github.com/Fuzss/pickupnotifier-fabric/files/7655192/latest.log)

**Comment by Fuzss** [comment]
Could you please try [Puzzles Lib](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib-fabric) v2.0.2? For me the issue is fixed with this version.

**Comment by jdamboeck** [comment]
So the minimal installation with:
- ForgeConfigAPIPort-v2.0.0-1.17.1-Fabric.jar
- PuzzlesLib-v2.0.2-1.17.1-Fabric.jar
- fabric-api-0.44.0+1.17.jar
- modmenu-2.0.14.jar
- PickUpNotifier-v2.1.0-1.17.1-Fabric.jar
- EasyMagic-v2.0.2-1.17.1-Fabric.jar

won't work with the new puzzles lib.
[2021-12-06-1.log](https://github.com/Fuzss/pickupnotifier-fabric/files/7658533/2021-12-06-1.log)

But when i throw it into my fully modded folder the pickupnotifier now works.
Installed mods:
- sodium-fabric-mc1.17.1-0.3.3+build.8.jar
- RoughlyEnoughItems-6.2.335.jar
- betterdarkmode-1.0.2-v20211004.jar
- MouseTweaks-fabric-mc1.17.1-2.15.jar
- continuity-1.0.3+1.17.jar
- lithium-fabric-mc1.17.1-0.7.5.jar
- sodium-extra-mc1.17.1-0.3.6.jar
- ForgeConfigAPIPort-v2.0.0-1.17.1-Fabric.jar
- indium-1.0.1+mc1.17.1.jar
- PuzzlesLib-v2.0.2-1.17.1-Fabric.jar
- cem-0.6.2.jar
- fabric-api-0.44.0+1.17.jar
- particle-rain-1.5.0.jar
- advancementinfo-1.17.1-fabric0.36.1-1.3.jar
- EntityCulling-Fabric-1.3.3.jar
- modmenu-2.0.14.jar
- cloth-api-2.0.54.jar
- enhancedblockentities-0.5+1.17.jar
- Xaeros_Minimap_21.22.3_Fabric_1.17.1.jar
- autorun-1.17.X-0.3.0.jar
- wthit-fabric-3.11.2.jar
- lazydfu-0.1.2.jar
- PresenceFootsteps-r35-1.17.jar
- cloth-config-5.1.40-fabric.jar
- PickUpNotifier-v2.1.0-1.17.1-Fabric.jar
- arrp-0.5.4.jar
- phosphor-fabric-mc1.17.x-0.8.0.jar
- slight-gui-modifications-2.0.2.jar
- SmoothScrollingEverywhere-3.0.3-unstable.jar
- dynamic-fps-2.0.6.jar
- FallingTree-1.17.1-2.14.5.jar
- lambdynamiclights-2.1.0+1.17.jar
- completeconfig-lib-1.2.0.jar
- fabrishot-1.5.1.jar
- reeses_sodium_options-mc1.17.1-1.2.3.jar
- animatica-0.1+1.17.jar
- EasyMagic-v2.0.2-1.17.1-Fabric.jar
- XaerosWorldMap_1.18.4_Fabric_1.17.1.jar
- architectury-2.6.35.jar
- WI-Zoom-1.3-MC1.17.1.jar
- iris-mc1.17-1.1.3.jar
- CITResewn-0.8.1.jar
- tooltipfix-1.0.4-1.17.1.jar

**Comment by Fuzss** [comment]
That's odd. Everything made sense with the bug I found in Puzzles. Oh well.

https://mega.nz/file/TBt1GC7T#uS354SGzJ3DRWfxt9wp60dkE9VQisKgUYaiepenyMFQ
So I made custom version for you with a bunch of log output. Would be great if you could get that broken state again and then pick up a few items, arrows and xp orbs and send the log to me.

Also thanks a lot for helping out with this!

**Comment by jdamboeck** [comment]
Here ya go.
Log seems to indicate that it's rendering but it's still not showing on screen.

[latest.log](https://github.com/Fuzss/pickupnotifier-fabric/files/7659387/latest.log)

Again it seems strange that it is working now in the fully modded folder. Maybe an dependency you forgot to list or me forgot to install? Or another setting that is not default which would influence the placing onscreen?

**Comment by Fuzss** [comment]
Dependencies are all defined in the fabric mods json thing, the game wouldn't even launch if one were missing.

So last attempt, because I'm really running out of ideas. Here is another custom version which logs different information.
https://mega.nz/file/GRcW2L7I#Fq6tOcYPe7l-HVCE7M63_d2evMTNsNJGHGICWpUlqrw
There's also an update to Forge Config API Port ([v2.0.1](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric/files/3551754)).
Also please try to delete the old config file before trying again (found at `.minecraft/config/pickupnotifier-client.toml`)

**Comment by jdamboeck** [comment]
So here ya go again. Sorry to say it is not working.

[latest.log](https://github.com/Fuzss/pickupnotifier-fabric/files/7666423/latest.log)

One thing in the log output makes me think.
[08:42:39] [Render thread/INFO]: rendering entry: x 1374, y 876, alpha 0.0, screenWidth 1440, screenHeight 900
Is screenWidth and screenHeight supposed to be my resolution? i was running the game in fullscreen 1920x1200.

**Comment by Fuzss** [comment]
That is the scaled resolution (depending on the Gui Scale option). Doesn't matter anyways, only thing important about it that the values for x and y are less (just to see that entries don't render offscreen for some reason).

So that's really unfortunate. Guess I could keep spamming you with test versions and we'd probably find the issue at some point, but I don't think that's worth the time, especially since everything is working when part of a mod pack.

I'll close the issue, but feel free to tell me in case you make any new discoveries. And thanks again for staying with me on this!
